/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;

/**
 * Generic class as container for a list of either roles, tasks or teams (by list of UIListItems)
 * 
 * @author kekema
 *
 */
public class UIAssignments extends UIAssignmentsBase
{
    public UIAssignments()
    {
        this((BusObjectConfig)null);
    }

    public UIAssignments(BusObjectConfig config)
    {
        super(config);
    }

    public void onInsert()
    {
    	// N.A.    	
    }

    public void onUpdate()
    {
    	// N.A.     	
    }

    public void onDelete()
    {
    	// N.A.     	
    }

}
