/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;


public abstract class UITaskUsersBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_TaskID = "TaskID";
    private final static String REL_Users = "COMP:Users";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UITaskUsers.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskID);
                ai.setJavaName(ATTR_TaskID);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_Users);
                ri.setName("Users");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UITaskUsers.Users.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public UITaskUsersBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getTaskID()
    {
        return getStringProperty(ATTR_TaskID);
    }

    public void setTaskID(String value)
    {
        setProperty(ATTR_TaskID, value, 0);
    }

    public UITaskUsers.Users getUsersObject()
    {
        return (UITaskUsers.Users)getSingleRelationObject(REL_Users);
    }

    public UITaskUsers.Users setUsersObject(UITaskUsers.Users a_Users)
    {
        return(UITaskUsers.Users)_getSingleRelation(REL_Users, true).setLocalObject(a_Users);
    }


    public static abstract class UsersBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
    {
        // tags used in the XML document
        private final static String REL_User = "COMP:User";
        private static ClassInfo s_classInfo = null;
        public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
        {
            if ( s_classInfo == null )//NOPMD
            {
                s_classInfo = newClassInfo(UITaskUsers.Users.class);
                s_classInfo.setUIDElements(new String[]{});
                {
                    RelationInfo_Composite ri = new RelationInfo_Composite(REL_User);
                    ri.setName("User");
                    ri.setMultiOcc(true);
                    ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UITaskUsers.Users.User.class);
                    s_classInfo.addRelationInfo(ri);
                }
            }
            return s_classInfo;
        }

        public UsersBase(BusObjectConfig config)
        {
            super(config);
        }

        public BusObjectIterator<UITaskUsers.Users.User> getUserObjects()
        {
            return getMultiRelationObjects(REL_User);
        }

        public UITaskUsers.Users.User addUserObject(UITaskUsers.Users.User a_User)
        {
            return (UITaskUsers.Users.User)_getMultiRelation(REL_User, true).addObject(a_User);
        }

        public void removeUserObject(UITaskUsers.Users.User a_User)
        {
            _getMultiRelation(REL_User, true).removeObject(a_User);
        }

        public static abstract class UserBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
        {
            // tags used in the XML document
            public final static String ATTR_SeqNo = "SeqNo";
            public final static String ATTR_OrgUserDN = "OrgUserDN";
            public final static String ATTR_Description = "Description";
            public final static String ATTR_Assigned = "Assigned";
            private static ClassInfo s_classInfo = null;
            public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
            {
                if ( s_classInfo == null )//NOPMD
                {
                    s_classInfo = newClassInfo(UITaskUsers.Users.User.class);
                    s_classInfo.setUIDElements(new String[]{});
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_SeqNo);
                        ai.setJavaName(ATTR_SeqNo);
                        ai.setAttributeClass(int.class);
                        NumberValidator v = new NumberValidator(ATTR_SeqNo);
                        ai.addConstraintHandler(v);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_OrgUserDN);
                        ai.setJavaName(ATTR_OrgUserDN);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_Description);
                        ai.setJavaName(ATTR_Description);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_Assigned);
                        ai.setJavaName(ATTR_Assigned);
                        ai.setAttributeClass(boolean.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                }
                return s_classInfo;
            }

            public UserBase(BusObjectConfig config)
            {
                super(config);
            }

            public int getSeqNo()
            {
                return getIntProperty(ATTR_SeqNo);
            }

            public void setSeqNo(int value)
            {
                setProperty(ATTR_SeqNo, value, 0);
            }

            public String getOrgUserDN()
            {
                return getStringProperty(ATTR_OrgUserDN);
            }

            public void setOrgUserDN(String value)
            {
                setProperty(ATTR_OrgUserDN, value, 0);
            }

            public String getDescription()
            {
                return getStringProperty(ATTR_Description);
            }

            public void setDescription(String value)
            {
                setProperty(ATTR_Description, value, 0);
            }

            public boolean getAssigned()
            {
                return getBooleanProperty(ATTR_Assigned);
            }

            public void setAssigned(boolean value)
            {
                setProperty(ATTR_Assigned, value, 0);
            }

        }
    }
}
