/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import java.util.ArrayList;
import java.util.HashMap;

import com.cordys.coe.tools.useradmin.util.Util;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;


/**
 * Domain class for Tasks
 * 
 * @author kekema
 *
 */
public class Tasks extends TasksBase
{
    public Tasks()
    {
        this((BusObjectConfig)null);
    }

    public Tasks(BusObjectConfig config)
    {
        super(config);
    }
    
    /**
     * Insert/Delete user tasks
     * 
     * @param orgUserDN
     * @param tasks
     */
    public static void maintainTasks(String orgUserDN, Tasks assignTasks, Tasks unassignTasks)
    {
    	ArrayList<String> assignTaskIDs = null;
    	ArrayList<String> unassignTaskIDs = null;
    	if (assignTasks != null)
    	{
    		assignTaskIDs = assignTasks.getTaskIDs();
    	}
    	if (unassignTasks != null)
    	{
    		unassignTaskIDs = unassignTasks.getTaskIDs();
    	}
    	com.cordys.coe.tools.useradmin.cordys.Task.maintainTasks(orgUserDN, assignTaskIDs, unassignTaskIDs);
    }
    
    /**
     * Assign inner tasks to user
     * 
     * @param orgUserDN
     */
    public void assignToUser(String orgUserDN)
    {
    	ArrayList<String> taskIDs = getTaskIDs();
    	com.cordys.coe.tools.useradmin.cordys.Task.maintainTasks(orgUserDN, taskIDs, null);
    }
    
    /**
     * Unassign inner tasks from user
     * 
     * @param orgUserDN
     */
    public void unassignFromUser(String orgUserDN)
    {
    	ArrayList<String> taskIDs = getTaskIDs();
    	com.cordys.coe.tools.useradmin.cordys.Task.maintainTasks(orgUserDN, null, taskIDs);
    }
    
    /**
     * Translate the inner busobject iterator of tasks to an arraylist of taskIDs
     * 
     * @return
     */
    public ArrayList<String> getTaskIDs()
    {
    	ArrayList<String> result = new ArrayList<String>();
    	HashMap<String, String> allTaskIDsByName = null;
    	BusObjectIterator<Task> tasks = getTaskObjects();
    	if (tasks.hasMoreElements())
    	{
    		// get hashmap of taskIDs by task name
    		allTaskIDsByName = com.cordys.coe.tools.useradmin.cordys.Task.getAllTaskIDsByName(false);
    	}
    	while (tasks.hasMoreElements())
    	{
    		// for each task, take the taskID, or if that one is empty, 
    		// determine the task ID for the task name
    		Task task = (Task)tasks.nextElement();
    		String taskID = null;
    		if (Util.isSet(task.getID()))
    		{
    			taskID = task.getID();
    		}
    		else if (Util.isSet(task.getName()))
    		{
    			taskID = allTaskIDsByName.get(task.getName());
    		}
    		if (Util.isSet(taskID))
    		{
    			result.add(taskID);
    		}
    	}
    	return result;
    }

    public void onInsert()
    {
    	// N.A.
    }

    public void onUpdate()
    {
    	// N.A.
    }

    public void onDelete()
    {
    	// N.A.
    }

}
