/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


/**
 * Class to contain user data for insert/update
 * 
 * @author kekema
 *
 */
public class UserUpdateData extends UserUpdateDataBase
{
    public UserUpdateData()
    {
        this((BusObjectConfig)null);
    }

    public UserUpdateData(BusObjectConfig config)
    {
        super(config);
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
