/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;


public abstract class UserUpdateDataBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_UserName = "UserName";
    public final static String ATTR_FullName = "FullName";
    public final static String ATTR_AuthenticationType = "AuthenticationType";
    public final static String ATTR_Password = "Password";
    public final static String ATTR_Address = "Address";
    public final static String ATTR_Company = "Company";
    public final static String ATTR_Telephone = "Telephone";
    public final static String ATTR_Fax = "Fax";
    public final static String ATTR_Email = "Email";
    private final static String REL_Roles = "AGGR:Roles";
    private final static String REL_Tasks = "AGGR:Tasks";
    private final static String REL_Teams = "AGGR:Teams";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UserUpdateData.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UserName);
                ai.setJavaName(ATTR_UserName);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FullName);
                ai.setJavaName(ATTR_FullName);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AuthenticationType);
                ai.setJavaName(ATTR_AuthenticationType);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Password);
                ai.setJavaName(ATTR_Password);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Address);
                ai.setJavaName(ATTR_Address);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Company);
                ai.setJavaName(ATTR_Company);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Telephone);
                ai.setJavaName(ATTR_Telephone);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Fax);
                ai.setJavaName(ATTR_Fax);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Email);
                ai.setJavaName(ATTR_Email);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_Roles);
                ri.setName("Roles");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.Roles.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_Tasks);
                ri.setName("Tasks");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.Tasks.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_Teams);
                ri.setName("Teams");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.Teams.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public UserUpdateDataBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getUserName()
    {
        return getStringProperty(ATTR_UserName);
    }

    public void setUserName(String value)
    {
        setProperty(ATTR_UserName, value, 0);
    }

    public String getFullName()
    {
        return getStringProperty(ATTR_FullName);
    }

    public void setFullName(String value)
    {
        setProperty(ATTR_FullName, value, 0);
    }

    public String getAuthenticationType()
    {
        return getStringProperty(ATTR_AuthenticationType);
    }

    public void setAuthenticationType(String value)
    {
        setProperty(ATTR_AuthenticationType, value, 0);
    }

    public String getPassword()
    {
        return getStringProperty(ATTR_Password);
    }

    public void setPassword(String value)
    {
        setProperty(ATTR_Password, value, 0);
    }

    public String getAddress()
    {
        return getStringProperty(ATTR_Address);
    }

    public void setAddress(String value)
    {
        setProperty(ATTR_Address, value, 0);
    }

    public String getCompany()
    {
        return getStringProperty(ATTR_Company);
    }

    public void setCompany(String value)
    {
        setProperty(ATTR_Company, value, 0);
    }

    public String getTelephone()
    {
        return getStringProperty(ATTR_Telephone);
    }

    public void setTelephone(String value)
    {
        setProperty(ATTR_Telephone, value, 0);
    }

    public String getFax()
    {
        return getStringProperty(ATTR_Fax);
    }

    public void setFax(String value)
    {
        setProperty(ATTR_Fax, value, 0);
    }

    public String getEmail()
    {
        return getStringProperty(ATTR_Email);
    }

    public void setEmail(String value)
    {
        setProperty(ATTR_Email, value, 0);
    }

    public Roles getRolesObject()
    {
        return (Roles)getSingleRelationObject(REL_Roles);
    }

    public Roles setRolesObject(Roles a_Roles)
    {
        return(Roles)_getSingleRelation(REL_Roles, true).setLocalObject(a_Roles);
    }

    public Tasks getTasksObject()
    {
        return (Tasks)getSingleRelationObject(REL_Tasks);
    }

    public Tasks setTasksObject(Tasks a_Tasks)
    {
        return(Tasks)_getSingleRelation(REL_Tasks, true).setLocalObject(a_Tasks);
    }

    public Teams getTeamsObject()
    {
        return (Teams)getSingleRelationObject(REL_Teams);
    }

    public Teams setTeamsObject(Teams a_Teams)
    {
        return(Teams)_getSingleRelation(REL_Teams, true).setLocalObject(a_Teams);
    }

}
