/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;


public abstract class UIAuthUserBasicBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_DN = "DN";
    public final static String ATTR_Description = "Description";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UIAuthUserBasic.class);
            s_classInfo.setUIDElements(new String[]{ATTR_DN});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DN);
                ai.setJavaName(ATTR_DN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Description);
                ai.setJavaName(ATTR_Description);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public UIAuthUserBasicBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getDN()
    {
        return getStringProperty(ATTR_DN);
    }

    public void setDN(String value)
    {
        setProperty(ATTR_DN, value, 0);
    }

    public String getDescription()
    {
        return getStringProperty(ATTR_Description);
    }

    public void setDescription(String value)
    {
        setProperty(ATTR_Description, value, 0);
    }


}
