/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import java.util.Vector;

import com.cordys.coe.tools.useradmin.cordys.CordysUser;
import com.cordys.coe.tools.useradmin.cordys.XMLStore;
import com.cordys.coe.tools.useradmin.exception.UserAdminException;
import com.cordys.coe.tools.useradmin.util.XMLObject;
import com.cordys.cpc.bsf.busobject.BSF;
import com.cordys.cpc.bsf.busobject.BusObjectArray;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.eibus.xml.nom.Node;
import com.eibus.xml.xpath.XPath;


/**
 * Class represents a UI user entry as derived from a user in the export file.
 * 
 * @author kekema
 *
 */
public class UIImportUser extends UIImportUserBase
{
    public UIImportUser()
    {
        this((BusObjectConfig)null);
    }

    public UIImportUser(BusObjectConfig config)
    {
        super(config);
    }

    /**
     * Get all users as defined in the export file.
     * The export file is expected in XMLStore as per the key.
     * 
     * @param key
     * @return
     */
    public static BusObjectIterator<UIImportUser> getUIImportUserObjects(String key)
    {
        Vector<UIImportUser> result = new Vector<UIImportUser>();
        
        XMLObject cordysExport = null;
    	try
    	{
    		cordysExport = XMLStore.getXMLObject(key);
            if (cordysExport != null)
    	    {
		        int cordysExportNode = cordysExport.getNOMNode();
				int[] userNodes = XPath.getMatchingNodes(".//Users/User", null, cordysExportNode);
		        for (int userNode : userNodes) 
		        {
		        	UIImportUser uiImportUser = new UIImportUser();
		        	uiImportUser.makeTransient();
		        	String orgUserDN = Node.getAttribute(userNode, "dn");
		        	orgUserDN = orgUserDN.replace("$organization", BSF.getOrganization());
		        	uiImportUser.setOrgUserDN(orgUserDN);
		        	uiImportUser.setDescription(Node.getAttribute(userNode, "description"));
		        	uiImportUser.setIsExistingUser(CordysUser.organizationalUserExists(orgUserDN));
		        	result.add(uiImportUser);
		        }
    	    }
            else
            {
            	throw new UserAdminException("Export of Cordys users not found in XMLStore (" + key + ")");
            }
        }
        finally
        {
        	if (cordysExport != null)
        	{
        		cordysExport.freeXMLMemory();
        	}
        }
        
        return new BusObjectArray<UIImportUser>(result);
    }

    public void onInsert()
    {
    	// N.A.
    }

    public void onUpdate()
    {
    	// N.A.    	
    }

    public void onDelete()
    {
    	// N.A.    	
    }

}
