/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;


public abstract class UIImportUserBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_OrgUserDN = "OrgUserDN";
    public final static String ATTR_Description = "Description";
    public final static String ATTR_IsExistingUser = "IsExistingUser";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UIImportUser.class);
            s_classInfo.setUIDElements(new String[]{ATTR_OrgUserDN});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OrgUserDN);
                ai.setJavaName(ATTR_OrgUserDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Description);
                ai.setJavaName(ATTR_Description);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_IsExistingUser);
                ai.setJavaName(ATTR_IsExistingUser);
                ai.setAttributeClass(boolean.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public UIImportUserBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getOrgUserDN()
    {
        return getStringProperty(ATTR_OrgUserDN);
    }

    public void setOrgUserDN(String value)
    {
        setProperty(ATTR_OrgUserDN, value, 0);
    }

    public String getDescription()
    {
        return getStringProperty(ATTR_Description);
    }

    public void setDescription(String value)
    {
        setProperty(ATTR_Description, value, 0);
    }

    public boolean getIsExistingUser()
    {
        return getBooleanProperty(ATTR_IsExistingUser);
    }

    public void setIsExistingUser(boolean value)
    {
        setProperty(ATTR_IsExistingUser, value, 0);
    }


}
