/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;

/**
 * Class for containing the data needed to synchronize an ext user into Cordys.
 * This includes roles, tasks and team assignmnents.
 * 
 * @author kekema
 *
 */
public class UISyncUserData extends UISyncUserDataBase
{
    public UISyncUserData()
    {
        this((BusObjectConfig)null);
    }

    public UISyncUserData(BusObjectConfig config)
    {
        super(config);
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
