/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;


public abstract class UITaskBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_SeqNo = "SeqNo";
    public final static String ATTR_TaskID = "TaskID";
    public final static String ATTR_Name = "Name";
    public final static String ATTR_TaskType = "TaskType";
    public final static String ATTR_Assigned = "Assigned";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UITask.class);
            s_classInfo.setUIDElements(new String[]{ATTR_TaskID});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SeqNo);
                ai.setJavaName(ATTR_SeqNo);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_SeqNo);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskID);
                ai.setJavaName(ATTR_TaskID);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Name);
                ai.setJavaName(ATTR_Name);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_TaskType);
                ai.setJavaName(ATTR_TaskType);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Assigned);
                ai.setJavaName(ATTR_Assigned);
                ai.setAttributeClass(boolean.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public UITaskBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getSeqNo()
    {
        return getIntProperty(ATTR_SeqNo);
    }

    public void setSeqNo(int value)
    {
        setProperty(ATTR_SeqNo, value, 0);
    }

    public String getTaskID()
    {
        return getStringProperty(ATTR_TaskID);
    }

    public void setTaskID(String value)
    {
        setProperty(ATTR_TaskID, value, 0);
    }

    public String getName()
    {
        return getStringProperty(ATTR_Name);
    }

    public void setName(String value)
    {
        setProperty(ATTR_Name, value, 0);
    }

    public String getTaskType()
    {
        return getStringProperty(ATTR_TaskType);
    }

    public void setTaskType(String value)
    {
        setProperty(ATTR_TaskType, value, 0);
    }

    public boolean getAssigned()
    {
        return getBooleanProperty(ATTR_Assigned);
    }

    public void setAssigned(boolean value)
    {
        setProperty(ATTR_Assigned, value, 0);
    }

}
