/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


/**
 * Class which can be used to populate user update data in the form of a list 
 * of roles, tasks or teams (nested UIAssignments with list of UIListItem)
 * 
 * @author kekema
 *
 */
public class UIUserUpdateData extends UIUserUpdateDataBase
{
    public UIUserUpdateData()
    {
        this((BusObjectConfig)null);
    }

    public UIUserUpdateData(BusObjectConfig config)
    {
        super(config);
    }

    public void onInsert()
    {
    	// N.A.
    }

    public void onUpdate()
    {
    	// N.A.    	
    }

    public void onDelete()
    {
    	// N.A.    	
    }

}
