/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.coe.tools.useradmin.cordys.CordysInstallation;
import com.cordys.coe.tools.useradmin.cordys.CordysUser;
import com.cordys.coe.tools.useradmin.cordys.CordysVersion;
import com.cordys.coe.tools.useradmin.exception.UserAdminException;
import com.cordys.cpc.bsf.busobject.BSF;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;


/**
 * UI class to support UserAdmin UI
 * 
 * @author kekema
 *
 */
public class UIUserAdmin extends UIUserAdminBase
{
    public UIUserAdmin()
    {
        this((BusObjectConfig)null);
    }

    public UIUserAdmin(BusObjectConfig config)
    {
        super(config);
    }

    public static void initUserAdmin()
    {
        if (!CordysUser.userIsOrgAdmin(BSF.getUser()))
        {
        	throw new UserAdminException("You need to be an Organizational Admin to use the User Admin.");
        }
        else
        {
        	CordysVersion cordysVersion = CordysInstallation.getVersion();
        	int major = cordysVersion.getIntMajor();
        	int minor = cordysVersion.getIntMinor();
        	if ((major != 4) || (minor != 4))
        	{
        		throw new UserAdminException("Platform version is " + cordysVersion.getFormattedExternal() + " - this version of User Admin supports OpenTexct Cordys 10.5");
        	}
        }
    }

    public void onInsert()
    {
    	// N.A.
    }

    public void onUpdate()
    {
    	// N.A.    	
    }

    public void onDelete()
    {
    	// N.A.    	
    }

}
