/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;


public abstract class UIUserTasksBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_OrgUserDN = "OrgUserDN";
    private final static String REL_RoleTasks = "COMP:RoleTasks";
    private final static String REL_UITasks = "COMP:UITasks";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UIUserTasks.class);
            s_classInfo.setUIDElements(new String[]{ATTR_OrgUserDN});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OrgUserDN);
                ai.setJavaName(ATTR_OrgUserDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_RoleTasks);
                ri.setName("RoleTasks");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UIUserTasks.RoleTasks.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_UITasks);
                ri.setName("UITasks");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UIUserTasks.UITasks.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public UIUserTasksBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getOrgUserDN()
    {
        return getStringProperty(ATTR_OrgUserDN);
    }

    public void setOrgUserDN(String value)
    {
        setProperty(ATTR_OrgUserDN, value, 0);
    }

    public UIUserTasks.RoleTasks getRoleTasksObject()
    {
        return (UIUserTasks.RoleTasks)getSingleRelationObject(REL_RoleTasks);
    }

    public UIUserTasks.RoleTasks setRoleTasksObject(UIUserTasks.RoleTasks a_RoleTasks)
    {
        return(UIUserTasks.RoleTasks)_getSingleRelation(REL_RoleTasks, true).setLocalObject(a_RoleTasks);
    }

    public UIUserTasks.UITasks getUITasksObject()
    {
        return (UIUserTasks.UITasks)getSingleRelationObject(REL_UITasks);
    }

    public UIUserTasks.UITasks setUITasksObject(UIUserTasks.UITasks a_UITasks)
    {
        return(UIUserTasks.UITasks)_getSingleRelation(REL_UITasks, true).setLocalObject(a_UITasks);
    }


    public static abstract class RoleTasksBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
    {
        // tags used in the XML document
        private final static String REL_RoleTask = "AGGR:RoleTask";
        private static ClassInfo s_classInfo = null;
        public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
        {
            if ( s_classInfo == null )//NOPMD
            {
                s_classInfo = newClassInfo(UIUserTasks.RoleTasks.class);
                s_classInfo.setUIDElements(new String[]{});
                {
                    RelationInfo_Composite ri = new RelationInfo_Composite(REL_RoleTask);
                    ri.setName("RoleTask");
                    ri.setMultiOcc(true);
                    ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UITask.class);
                    s_classInfo.addRelationInfo(ri);
                }
            }
            return s_classInfo;
        }

        public RoleTasksBase(BusObjectConfig config)
        {
            super(config);
        }

        public BusObjectIterator<UITask> getRoleTaskObjects()
        {
            return getMultiRelationObjects(REL_RoleTask);
        }

        public UITask addRoleTaskObject(UITask a_UITask)
        {
            return (UITask)_getMultiRelation(REL_RoleTask, true).addObject(a_UITask);
        }

        public void removeRoleTaskObject(UITask a_UITask)
        {
            _getMultiRelation(REL_RoleTask, true).removeObject(a_UITask);
        }

    }
    public static abstract class UITasksBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
    {
        // tags used in the XML document
        private final static String REL_UITask = "AGGR:UITask";
        private static ClassInfo s_classInfo = null;
        public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
        {
            if ( s_classInfo == null )//NOPMD
            {
                s_classInfo = newClassInfo(UIUserTasks.UITasks.class);
                s_classInfo.setUIDElements(new String[]{});
                {
                    RelationInfo_Composite ri = new RelationInfo_Composite(REL_UITask);
                    ri.setName("UITask");
                    ri.setMultiOcc(true);
                    ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UITask.class);
                    s_classInfo.addRelationInfo(ri);
                }
            }
            return s_classInfo;
        }

        public UITasksBase(BusObjectConfig config)
        {
            super(config);
        }

        public BusObjectIterator<UITask> getUITaskObjects()
        {
            return getMultiRelationObjects(REL_UITask);
        }

        public UITask addUITaskObject(UITask a_UITask)
        {
            return (UITask)_getMultiRelation(REL_UITask, true).addObject(a_UITask);
        }

        public void removeUITaskObject(UITask a_UITask)
        {
            _getMultiRelation(REL_UITask, true).removeObject(a_UITask);
        }

    }
}
