/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;


public abstract class UIExtUserBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_ExtUserDN = "ExtUserDN";
    public final static String ATTR_Description = "Description";
    public final static String ATTR_ExtGroupDN = "ExtGroupDN";
    public final static String ATTR_Group = "Group";
    public final static String ATTR_IsCordysUser = "IsCordysUser";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UIExtUser.class);
            s_classInfo.setUIDElements(new String[]{ATTR_ExtUserDN});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ExtUserDN);
                ai.setJavaName(ATTR_ExtUserDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Description);
                ai.setJavaName(ATTR_Description);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ExtGroupDN);
                ai.setJavaName(ATTR_ExtGroupDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Group);
                ai.setJavaName(ATTR_Group);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_IsCordysUser);
                ai.setJavaName(ATTR_IsCordysUser);
                ai.setAttributeClass(boolean.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public UIExtUserBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getExtUserDN()
    {
        return getStringProperty(ATTR_ExtUserDN);
    }

    public void setExtUserDN(String value)
    {
        setProperty(ATTR_ExtUserDN, value, 0);
    }

    public String getDescription()
    {
        return getStringProperty(ATTR_Description);
    }

    public void setDescription(String value)
    {
        setProperty(ATTR_Description, value, 0);
    }

    public String getExtGroupDN()
    {
        return getStringProperty(ATTR_ExtGroupDN);
    }

    public void setExtGroupDN(String value)
    {
        setProperty(ATTR_ExtGroupDN, value, 0);
    }

    public String getGroup()
    {
        return getStringProperty(ATTR_Group);
    }

    public void setGroup(String value)
    {
        setProperty(ATTR_Group, value, 0);
    }

    public boolean getIsCordysUser()
    {
        return getBooleanProperty(ATTR_IsCordysUser);
    }

    public void setIsCordysUser(boolean value)
    {
        setProperty(ATTR_IsCordysUser, value, 0);
    }



}
