/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;


public abstract class UIListItemBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_SeqNo = "SeqNo";
    public final static String ATTR_DN = "DN";
    public final static String ATTR_ID = "ID";
    public final static String ATTR_Description = "Description";
    public final static String ATTR_LongDescription = "LongDescription";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UIListItem.class);
            s_classInfo.setUIDElements(new String[]{ATTR_SeqNo});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_SeqNo);
                ai.setJavaName(ATTR_SeqNo);
                ai.setAttributeClass(int.class);
                NumberValidator v = new NumberValidator(ATTR_SeqNo);
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DN);
                ai.setJavaName(ATTR_DN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ID);
                ai.setJavaName(ATTR_ID);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Description);
                ai.setJavaName(ATTR_Description);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_LongDescription);
                ai.setJavaName(ATTR_LongDescription);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public UIListItemBase(BusObjectConfig config)
    {
        super(config);
    }

    public int getSeqNo()
    {
        return getIntProperty(ATTR_SeqNo);
    }

    public void setSeqNo(int value)
    {
        setProperty(ATTR_SeqNo, value, 0);
    }

    public String getDN()
    {
        return getStringProperty(ATTR_DN);
    }

    public void setDN(String value)
    {
        setProperty(ATTR_DN, value, 0);
    }

    public String getID()
    {
        return getStringProperty(ATTR_ID);
    }

    public void setID(String value)
    {
        setProperty(ATTR_ID, value, 0);
    }

    public String getDescription()
    {
        return getStringProperty(ATTR_Description);
    }

    public void setDescription(String value)
    {
        setProperty(ATTR_Description, value, 0);
    }

    public String getLongDescription()
    {
        return getStringProperty(ATTR_LongDescription);
    }

    public void setLongDescription(String value)
    {
        setProperty(ATTR_LongDescription, value, 0);
    }


}
