/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.coe.tools.useradmin.cordys.Role;
import com.cordys.coe.tools.useradmin.cordys.Task;
import com.cordys.coe.tools.useradmin.util.Util;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;


public class UIRole extends UIRoleBase
{
    public UIRole()
    {
        this((BusObjectConfig)null);
    }

    public UIRole(BusObjectConfig config)
    {
        super(config);
    }

    public static void addRole(String roleName)
    {
    	if (Util.isSet(roleName))
    	{
    		Role.addRole(roleName);
    	}
    }
    
    public static void deleteRole(String roleDN)
    {
    	if (Util.isSet(roleDN))
    	{
    		try
    		{
    			Task.deleteAllAssignedTasksForDN(roleDN);
    		}
			catch (Exception e)
			{
				// ignore
			}
    		Role.deleteRole(roleDN);
    	}
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
