/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;


public abstract class UIRoleTasksBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_RoleDN = "RoleDN";
    private final static String REL_RoleTasks = "COMP:RoleTasks";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UIRoleTasks.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_RoleDN);
                ai.setJavaName(ATTR_RoleDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_RoleTasks);
                ri.setName("RoleTasks");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UIRoleTasks.RoleTasks.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public UIRoleTasksBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getRoleDN()
    {
        return getStringProperty(ATTR_RoleDN);
    }

    public void setRoleDN(String value)
    {
        setProperty(ATTR_RoleDN, value, 0);
    }

    public UIRoleTasks.RoleTasks getRoleTasksObject()
    {
        return (UIRoleTasks.RoleTasks)getSingleRelationObject(REL_RoleTasks);
    }

    public UIRoleTasks.RoleTasks setRoleTasksObject(UIRoleTasks.RoleTasks a_RoleTasks)
    {
        return(UIRoleTasks.RoleTasks)_getSingleRelation(REL_RoleTasks, true).setLocalObject(a_RoleTasks);
    }


    public static abstract class RoleTasksBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
    {
        // tags used in the XML document
        private final static String REL_RoleTask = "AGGR:RoleTask";
        private static ClassInfo s_classInfo = null;
        public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
        {
            if ( s_classInfo == null )//NOPMD
            {
                s_classInfo = newClassInfo(UIRoleTasks.RoleTasks.class);
                s_classInfo.setUIDElements(new String[]{});
                {
                    RelationInfo_Composite ri = new RelationInfo_Composite(REL_RoleTask);
                    ri.setName("RoleTask");
                    ri.setMultiOcc(true);
                    ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UITask.class);
                    s_classInfo.addRelationInfo(ri);
                }
            }
            return s_classInfo;
        }

        public RoleTasksBase(BusObjectConfig config)
        {
            super(config);
        }

        public BusObjectIterator<UITask> getRoleTaskObjects()
        {
            return getMultiRelationObjects(REL_RoleTask);
        }

        public UITask addRoleTaskObject(UITask a_UITask)
        {
            return (UITask)_getMultiRelation(REL_RoleTask, true).addObject(a_UITask);
        }

        public void removeRoleTaskObject(UITask a_UITask)
        {
            _getMultiRelation(REL_RoleTask, true).removeObject(a_UITask);
        }

    }
}
