/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;


public abstract class UISyncUserDataBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_ExtGroupDN = "ExtGroupDN";
    private final static String REL_RoleAssignments = "AGGR:RoleAssignments";
    private final static String REL_TaskAssignments = "AGGR:TaskAssignments";
    private final static String REL_TeamAssignments = "AGGR:TeamAssignments";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UISyncUserData.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ExtGroupDN);
                ai.setJavaName(ATTR_ExtGroupDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_RoleAssignments);
                ri.setName("RoleAssignments");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UIAssignments.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_TaskAssignments);
                ri.setName("TaskAssignments");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UIAssignments.class);
                s_classInfo.addRelationInfo(ri);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_TeamAssignments);
                ri.setName("TeamAssignments");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UIAssignments.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public UISyncUserDataBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getExtGroupDN()
    {
        return getStringProperty(ATTR_ExtGroupDN);
    }

    public void setExtGroupDN(String value)
    {
        setProperty(ATTR_ExtGroupDN, value, 0);
    }

    public UIAssignments getRoleAssignmentsObject()
    {
        return (UIAssignments)getSingleRelationObject(REL_RoleAssignments);
    }

    public UIAssignments setRoleAssignmentsObject(UIAssignments a_UIAssignments)
    {
        return(UIAssignments)_getSingleRelation(REL_RoleAssignments, true).setLocalObject(a_UIAssignments);
    }

    public UIAssignments getTaskAssignmentsObject()
    {
        return (UIAssignments)getSingleRelationObject(REL_TaskAssignments);
    }

    public UIAssignments setTaskAssignmentsObject(UIAssignments a_UIAssignments)
    {
        return(UIAssignments)_getSingleRelation(REL_TaskAssignments, true).setLocalObject(a_UIAssignments);
    }

    public UIAssignments getTeamAssignmentsObject()
    {
        return (UIAssignments)getSingleRelationObject(REL_TeamAssignments);
    }

    public UIAssignments setTeamAssignmentsObject(UIAssignments a_UIAssignments)
    {
        return(UIAssignments)_getSingleRelation(REL_TeamAssignments, true).setLocalObject(a_UIAssignments);
    }

}
