/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;

/**
 * Inner class in UIUserTasks
 * 
 * @author kekema
 *
 */
public class UITask extends UITaskBase
{
    public UITask()
    {
        this((BusObjectConfig)null);
    }

    public UITask(BusObjectConfig config)
    {
        super(config);
    }

    public void onInsert()
    {
    	// N.A.
    }

    public void onUpdate()
    {
    	// N.A.
    }

    public void onDelete()
    {
    	// N.A.
    }
}
