/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;


public abstract class UITeamUsersBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_UnitID = "UnitID";
    private final static String REL_Assignments = "COMP:Assignments";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UITeamUsers.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UnitID);
                ai.setJavaName(ATTR_UnitID);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_Assignments);
                ri.setName("Assignments");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UITeamUsers.Assignments.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public UITeamUsersBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getUnitID()
    {
        return getStringProperty(ATTR_UnitID);
    }

    public void setUnitID(String value)
    {
        setProperty(ATTR_UnitID, value, 0);
    }

    public UITeamUsers.Assignments getAssignmentsObject()
    {
        return (UITeamUsers.Assignments)getSingleRelationObject(REL_Assignments);
    }

    public UITeamUsers.Assignments setAssignmentsObject(UITeamUsers.Assignments a_Assignments)
    {
        return(UITeamUsers.Assignments)_getSingleRelation(REL_Assignments, true).setLocalObject(a_Assignments);
    }


    public static abstract class AssignmentsBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
    {
        // tags used in the XML document
        private final static String REL_Assignment = "COMP:Assignment";
        private static ClassInfo s_classInfo = null;
        public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
        {
            if ( s_classInfo == null )//NOPMD
            {
                s_classInfo = newClassInfo(UITeamUsers.Assignments.class);
                s_classInfo.setUIDElements(new String[]{});
                {
                    RelationInfo_Composite ri = new RelationInfo_Composite(REL_Assignment);
                    ri.setName("Assignment");
                    ri.setMultiOcc(true);
                    ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UITeamUsers.Assignments.Assignment.class);
                    s_classInfo.addRelationInfo(ri);
                }
            }
            return s_classInfo;
        }

        public AssignmentsBase(BusObjectConfig config)
        {
            super(config);
        }

        public BusObjectIterator<UITeamUsers.Assignments.Assignment> getAssignmentObjects()
        {
            return getMultiRelationObjects(REL_Assignment);
        }

        public UITeamUsers.Assignments.Assignment addAssignmentObject(UITeamUsers.Assignments.Assignment a_Assignment)
        {
            return (UITeamUsers.Assignments.Assignment)_getMultiRelation(REL_Assignment, true).addObject(a_Assignment);
        }

        public void removeAssignmentObject(UITeamUsers.Assignments.Assignment a_Assignment)
        {
            _getMultiRelation(REL_Assignment, true).removeObject(a_Assignment);
        }

        public static abstract class AssignmentBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
        {
            // tags used in the XML document
            public final static String ATTR_SeqNo = "SeqNo";
            public final static String ATTR_AssignmentID = "AssignmentID";
            public final static String ATTR_OrgUserDN = "OrgUserDN";
            public final static String ATTR_RoleDN = "RoleDN";
            public final static String ATTR_Description = "Description";
            public final static String ATTR_Assigned = "Assigned";
            private static ClassInfo s_classInfo = null;
            public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
            {
                if ( s_classInfo == null )//NOPMD
                {
                    s_classInfo = newClassInfo(UITeamUsers.Assignments.Assignment.class);
                    s_classInfo.setUIDElements(new String[]{});
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_SeqNo);
                        ai.setJavaName(ATTR_SeqNo);
                        ai.setAttributeClass(int.class);
                        NumberValidator v = new NumberValidator(ATTR_SeqNo);
                        ai.addConstraintHandler(v);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_AssignmentID);
                        ai.setJavaName(ATTR_AssignmentID);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_OrgUserDN);
                        ai.setJavaName(ATTR_OrgUserDN);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_RoleDN);
                        ai.setJavaName(ATTR_RoleDN);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_Description);
                        ai.setJavaName(ATTR_Description);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_Assigned);
                        ai.setJavaName(ATTR_Assigned);
                        ai.setAttributeClass(boolean.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                }
                return s_classInfo;
            }

            public AssignmentBase(BusObjectConfig config)
            {
                super(config);
            }

            public int getSeqNo()
            {
                return getIntProperty(ATTR_SeqNo);
            }

            public void setSeqNo(int value)
            {
                setProperty(ATTR_SeqNo, value, 0);
            }

            public String getAssignmentID()
            {
                return getStringProperty(ATTR_AssignmentID);
            }

            public void setAssignmentID(String value)
            {
                setProperty(ATTR_AssignmentID, value, 0);
            }

            public String getOrgUserDN()
            {
                return getStringProperty(ATTR_OrgUserDN);
            }

            public void setOrgUserDN(String value)
            {
                setProperty(ATTR_OrgUserDN, value, 0);
            }

            public String getRoleDN()
            {
                return getStringProperty(ATTR_RoleDN);
            }

            public void setRoleDN(String value)
            {
                setProperty(ATTR_RoleDN, value, 0);
            }

            public String getDescription()
            {
                return getStringProperty(ATTR_Description);
            }

            public void setDescription(String value)
            {
                setProperty(ATTR_Description, value, 0);
            }

            public boolean getAssigned()
            {
                return getBooleanProperty(ATTR_Assigned);
            }

            public void setAssigned(boolean value)
            {
                setProperty(ATTR_Assigned, value, 0);
            }

        }
    }
}
