/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.listeners.constraint.StringValidator;


public abstract class UIUserBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_OrgUserDN = "OrgUserDN";
    public final static String ATTR_AuthUserDN = "AuthUserDN";
    public final static String ATTR_UserName = "UserName";
    public final static String ATTR_FullUserName = "FullUserName";
    public final static String ATTR_UserID = "UserID";
    public final static String ATTR_Description = "Description";
    public final static String ATTR_Disabled = "Disabled";
    public final static String ATTR_AuthenticationType = "AuthenticationType";
    public final static String ATTR_UserPassword = "UserPassword";
    public final static String ATTR_ConfirmPassword = "ConfirmPassword";
    public final static String ATTR_DefaultOrg = "DefaultOrg";
    public final static String ATTR_Company = "Company";
    public final static String ATTR_Address = "Address";
    public final static String ATTR_Telephone = "Telephone";
    public final static String ATTR_Telephone2 = "Telephone2";
    public final static String ATTR_Email = "Email";
    public final static String ATTR_UserHomePage = "UserHomePage";
    public final static String ATTR_CloneOrgUserDN = "CloneOrgUserDN";
    public final static String ATTR_CloneRoles = "CloneRoles";
    public final static String ATTR_CloneTasks = "CloneTasks";
    public final static String ATTR_CloneTeams = "CloneTeams";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UIUser.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OrgUserDN);
                ai.setJavaName(ATTR_OrgUserDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AuthUserDN);
                ai.setJavaName(ATTR_AuthUserDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UserName);
                ai.setJavaName(ATTR_UserName);
                ai.setAttributeClass(String.class);
                ai.setRequired(true);
                StringValidator v = new StringValidator(ATTR_UserName);
                v.setPattern("^[^\\\\:/*?;,\\\"'&<>|#+=]*$");
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FullUserName);
                ai.setJavaName(ATTR_FullUserName);
                ai.setAttributeClass(String.class);
                ai.setRequired(true);
                StringValidator v = new StringValidator(ATTR_FullUserName);
                v.setPattern("^[^\\\\:/*?;,\\\"&<>|#+=]*$");
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UserID);
                ai.setJavaName(ATTR_UserID);
                ai.setAttributeClass(String.class);
                ai.setRequired(true);
                StringValidator v = new StringValidator(ATTR_UserID);
                v.setPattern("^[^\\\"]*$");
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Description);
                ai.setJavaName(ATTR_Description);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Disabled);
                ai.setJavaName(ATTR_Disabled);
                ai.setAttributeClass(boolean.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AuthenticationType);
                ai.setJavaName(ATTR_AuthenticationType);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UserPassword);
                ai.setJavaName(ATTR_UserPassword);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_ConfirmPassword);
                ai.setJavaName(ATTR_ConfirmPassword);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_DefaultOrg);
                ai.setJavaName(ATTR_DefaultOrg);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Company);
                ai.setJavaName(ATTR_Company);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Address);
                ai.setJavaName(ATTR_Address);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Telephone);
                ai.setJavaName(ATTR_Telephone);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Telephone);
                v.setPattern("^[^\\\\:/*?;,\\\"'&<>|#+@\\${}%]*$");
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Telephone2);
                ai.setJavaName(ATTR_Telephone2);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Telephone2);
                v.setPattern("^[^\\\\:/*?;,\\\"'&<>|#+@\\${}%]*$");
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Email);
                ai.setJavaName(ATTR_Email);
                ai.setAttributeClass(String.class);
                StringValidator v = new StringValidator(ATTR_Email);
                v.setPattern("[A-Za-z]+.+@.+.[A-Za-z]+");
                ai.addConstraintHandler(v);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UserHomePage);
                ai.setJavaName(ATTR_UserHomePage);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CloneOrgUserDN);
                ai.setJavaName(ATTR_CloneOrgUserDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CloneRoles);
                ai.setJavaName(ATTR_CloneRoles);
                ai.setAttributeClass(boolean.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CloneTasks);
                ai.setJavaName(ATTR_CloneTasks);
                ai.setAttributeClass(boolean.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_CloneTeams);
                ai.setJavaName(ATTR_CloneTeams);
                ai.setAttributeClass(boolean.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public UIUserBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getOrgUserDN()
    {
        return getStringProperty(ATTR_OrgUserDN);
    }

    public void setOrgUserDN(String value)
    {
        setProperty(ATTR_OrgUserDN, value, 0);
    }

    public String getAuthUserDN()
    {
        return getStringProperty(ATTR_AuthUserDN);
    }

    public void setAuthUserDN(String value)
    {
        setProperty(ATTR_AuthUserDN, value, 0);
    }

    public String getUserName()
    {
        return getStringProperty(ATTR_UserName);
    }

    public void setUserName(String value)
    {
        setProperty(ATTR_UserName, value, 0);
    }

    public String getFullUserName()
    {
        return getStringProperty(ATTR_FullUserName);
    }

    public void setFullUserName(String value)
    {
        setProperty(ATTR_FullUserName, value, 0);
    }

    public String getUserID()
    {
        return getStringProperty(ATTR_UserID);
    }

    public void setUserID(String value)
    {
        setProperty(ATTR_UserID, value, 0);
    }

    public String getDescription()
    {
        return getStringProperty(ATTR_Description);
    }

    public void setDescription(String value)
    {
        setProperty(ATTR_Description, value, 0);
    }

    public boolean getDisabled()
    {
        return getBooleanProperty(ATTR_Disabled);
    }

    public void setDisabled(boolean value)
    {
        setProperty(ATTR_Disabled, value, 0);
    }

    public String getAuthenticationType()
    {
        return getStringProperty(ATTR_AuthenticationType);
    }

    public void setAuthenticationType(String value)
    {
        setProperty(ATTR_AuthenticationType, value, 0);
    }

    public String getUserPassword()
    {
        return getStringProperty(ATTR_UserPassword);
    }

    public void setUserPassword(String value)
    {
        setProperty(ATTR_UserPassword, value, 0);
    }

    public String getConfirmPassword()
    {
        return getStringProperty(ATTR_ConfirmPassword);
    }

    public void setConfirmPassword(String value)
    {
        setProperty(ATTR_ConfirmPassword, value, 0);
    }

    public String getDefaultOrg()
    {
        return getStringProperty(ATTR_DefaultOrg);
    }

    public void setDefaultOrg(String value)
    {
        setProperty(ATTR_DefaultOrg, value, 0);
    }

    public String getCompany()
    {
        return getStringProperty(ATTR_Company);
    }

    public void setCompany(String value)
    {
        setProperty(ATTR_Company, value, 0);
    }

    public String getAddress()
    {
        return getStringProperty(ATTR_Address);
    }

    public void setAddress(String value)
    {
        setProperty(ATTR_Address, value, 0);
    }

    public String getTelephone()
    {
        return getStringProperty(ATTR_Telephone);
    }

    public void setTelephone(String value)
    {
        setProperty(ATTR_Telephone, value, 0);
    }

    public String getTelephone2()
    {
        return getStringProperty(ATTR_Telephone2);
    }

    public void setTelephone2(String value)
    {
        setProperty(ATTR_Telephone2, value, 0);
    }

    public String getEmail()
    {
        return getStringProperty(ATTR_Email);
    }

    public void setEmail(String value)
    {
        setProperty(ATTR_Email, value, 0);
    }

    public String getUserHomePage()
    {
        return getStringProperty(ATTR_UserHomePage);
    }

    public void setUserHomePage(String value)
    {
        setProperty(ATTR_UserHomePage, value, 0);
    }

    public String getCloneOrgUserDN()
    {
        return getStringProperty(ATTR_CloneOrgUserDN);
    }

    public void setCloneOrgUserDN(String value)
    {
        setProperty(ATTR_CloneOrgUserDN, value, 0);
    }

    public boolean getCloneRoles()
    {
        return getBooleanProperty(ATTR_CloneRoles);
    }

    public void setCloneRoles(boolean value)
    {
        setProperty(ATTR_CloneRoles, value, 0);
    }

    public boolean getCloneTasks()
    {
        return getBooleanProperty(ATTR_CloneTasks);
    }

    public void setCloneTasks(boolean value)
    {
        setProperty(ATTR_CloneTasks, value, 0);
    }

    public boolean getCloneTeams()
    {
        return getBooleanProperty(ATTR_CloneTeams);
    }

    public void setCloneTeams(boolean value)
    {
        setProperty(ATTR_CloneTeams, value, 0);
    }





}
