/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.coe.tools.useradmin.cordys.CordysUser;
import com.cordys.coe.tools.useradmin.exception.UserAdminException;
import com.cordys.cpc.bsf.busobject.BSF;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;


/**
 * UI class to support UserAdmin UI
 * 
 * @author kekema
 *
 */
public class UIUserAdmin extends UIUserAdminBase
{
    public UIUserAdmin()
    {
        this((BusObjectConfig)null);
    }

    public UIUserAdmin(BusObjectConfig config)
    {
        super(config);
    }

    public static void initUserAdmin()
    {
        if (!CordysUser.userIsOrgAdmin(BSF.getUser()))
        {
        	throw new UserAdminException("You need to be an Organizational Admin to use the User Admin.");
        }
    }

    public void onInsert()
    {
    	// N.A.
    }

    public void onUpdate()
    {
    	// N.A.    	
    }

    public void onDelete()
    {
    	// N.A.    	
    }

}
