/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;


public abstract class RolesBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    private final static String REL_Role = "AGGR:Role";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(Roles.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_Role);
                ri.setName("Role");
                ri.setMultiOcc(true);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.Role.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public RolesBase(BusObjectConfig config)
    {
        super(config);
    }

    public BusObjectIterator<Role> getRoleObjects()
    {
        return getMultiRelationObjects(REL_Role);
    }

    public Role addRoleObject(Role a_Role)
    {
        return (Role)_getMultiRelation(REL_Role, true).addObject(a_Role);
    }

    public void removeRoleObject(Role a_Role)
    {
        _getMultiRelation(REL_Role, true).removeObject(a_Role);
    }

}
