/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import java.util.ArrayList;
import java.util.HashMap;

import com.cordys.coe.tools.useradmin.util.Util;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;


/**
 * Domain class for user roles
 * 
 * @author kekema
 *
 */
public class Roles extends RolesBase
{
    public Roles()
    {
        this((BusObjectConfig)null);
    }

    public Roles(BusObjectConfig config)
    {
        super(config);
    }
    
    /**
     * Add / remove user role assignments
     * 
     * @param orgUserDN
     * @param assignRoles
     * @param unassignRoles
     */
    public static void maintainRoles(String orgUserDN, Roles assignRoles, Roles unassignRoles)
    {
    	ArrayList<String> assignRoleDNs = null;
    	ArrayList<String> unassignRoleDNs = null;
    	if (assignRoles != null)
    	{
    		assignRoleDNs = assignRoles.getRoleDNs();
    	}
    	if (unassignRoles != null)
    	{
    		unassignRoleDNs = unassignRoles.getRoleDNs();
    	}    
    	com.cordys.coe.tools.useradmin.cordys.Role.maintainUserRoles(orgUserDN, assignRoleDNs, unassignRoleDNs);
    }
    
    /**
     * Assign inner roles to user
     * 
     * @param orgUserDN
     */
    public void assignToUser(String orgUserDN)
    {
    	ArrayList<String> roleDNs = getRoleDNs();
    	com.cordys.coe.tools.useradmin.cordys.Role.maintainUserRoles(orgUserDN, roleDNs, null);
    }
    
    /**
     * Unassign inner roles from user
     * 
     * @param orgUserDN
     */
    public void unassignFromUser(String orgUserDN)
    {
    	ArrayList<String> roleDNs = getRoleDNs();
    	com.cordys.coe.tools.useradmin.cordys.Role.maintainUserRoles(orgUserDN, null, roleDNs);
    }
    
    /**
     * Translate the inner busobject iterator of roles to an arraylist of DNs
     * 
     * @return
     */
    public ArrayList<String> getRoleDNs()
    {
        HashMap<String, String> allRolesByName = null;
        ArrayList<String> result = new ArrayList<String>();  
        BusObjectIterator<Role> roles = getRoleObjects();
        if (roles.hasMoreElements())
        {
        	allRolesByName = com.cordys.coe.tools.useradmin.cordys.Role.getAllRolesByName();
        }
        while (roles.hasMoreElements())
        {
        	Role role = (Role)roles.nextElement();
        	String roleDN = role.getResultingDN(allRolesByName);
       		if (Util.isSet(roleDN))
    		{
    			result.add(roleDN);
    		}
        }
        return result;
    }

    public void onInsert()
    {
    	// N.A.
    }

    public void onUpdate()
    {
    	// N.A.
    }

    public void onDelete()
    {
    	// N.A.
    }

}
