/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import java.util.HashMap;

import com.cordys.coe.tools.useradmin.util.Util;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;


/**
 * Domain class for Role
 * 
 * @author kekema
 *
 */
public class Role extends RoleBase
{
    public Role()
    {
        this((BusObjectConfig)null);
    }

    public Role(BusObjectConfig config)
    {
        super(config);
    }
    
    /**
     * Derive the resulting DN for the role from DN attribute or Name attribute
     * 
     * @param allRolesByName
     * @return
     */
    public String getResultingDN(HashMap<String, String> allRolesByName)
    {
    	String roleDN = null;
		// if a DN is given, just take the value as is, else search the DN as per the name in the hashmap
    	if (Util.isSet(this.getDN()))
    	{
    		roleDN = this.getDN();
    	}
    	else
    	{
    		if (Util.isSet(this.getName()))
    		{
    			roleDN = allRolesByName.get(this.getName());
    		}
    	}
    	return roleDN;
    }

    public void onInsert()
    {
    	// N.A.
    }

    public void onUpdate()
    {
    	// N.A.    	
    }

    public void onDelete()
    {
    	// N.A.    	
    }

}
