/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;


public abstract class TasksBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    private final static String REL_Task = "AGGR:Task";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(Tasks.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_Task);
                ri.setName("Task");
                ri.setMultiOcc(true);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.Task.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public TasksBase(BusObjectConfig config)
    {
        super(config);
    }

    public BusObjectIterator<Task> getTaskObjects()
    {
        return getMultiRelationObjects(REL_Task);
    }

    public Task addTaskObject(Task a_Task)
    {
        return (Task)_getMultiRelation(REL_Task, true).addObject(a_Task);
    }

    public void removeTaskObject(Task a_Task)
    {
        _getMultiRelation(REL_Task, true).removeObject(a_Task);
    }

}
