/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;


/**
 * Domain class for Task 
 * 
 * @author kekema
 *
 */
public class Task extends TaskBase
{
    public Task()
    {
        this((BusObjectConfig)null);
    }

    public Task(BusObjectConfig config)
    {
        super(config);
    }

    public void onInsert()
    {
    }

    public void onUpdate()
    {
    }

    public void onDelete()
    {
    }

}
