/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import java.util.HashMap;

import com.cordys.coe.tools.useradmin.ui.UIListItem;
import com.cordys.coe.tools.useradmin.util.Util;
import com.cordys.cpc.bsf.busobject.BusObjectConfig;


/**
 * Domain class for Team (assignment)
 * 
 * @author kekema
 *
 */
public class Team extends TeamBase
{
    public Team()
    {
        this((BusObjectConfig)null);
    }

    public Team(BusObjectConfig config)
    {
        super(config);
    }
    
    /**
     * Derive the resulting Unit ID from UnitID attribute or UnitQN attribute
     * 
     * @param unitIDsByQName
     * @return
     */
    public String getResultingUnitID(HashMap<String, String> unitIDsByQName)
    {
		String unitID = this.getUnitID();
		String unitQN = this.getUnitQN();
		if (!Util.isSet(unitID) && (Util.isSet(unitQN)))
		{
			unitID = unitIDsByQName.get(unitQN);
		}
		return unitID;
    }
    
    /**
     * Derive a list item from the team assignment
     * 
     * @param unitIDsByQName
     * @param allRolesByName
     * @return
     */
    public UIListItem getListItem(HashMap<String, String> unitIDsByQName, HashMap<String, String> allRolesByName)
    {
		UIListItem listItem = null;
		String unitID = getResultingUnitID(unitIDsByQName);
		if (Util.isSet(unitID))
		{
			Role role = getRoleObject();
			String roleDN = role.getResultingDN(allRolesByName);
			if (Util.isSet(roleDN))
			{
				listItem = new UIListItem();
				listItem.makeTransient();
				listItem.setID(unitID);
				listItem.setDN(roleDN);
			}
		}
		return listItem;
    }

    public void onInsert()
    {
    	// N.A.
    }

    public void onUpdate()
    {
    	// N.A.
    }

    public void onDelete()
    {
    	// N.A.
    }

}
