/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;


public abstract class UserBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_OrgUserDN = "OrgUserDN";
    public final static String ATTR_AuthUserDN = "AuthUserDN";
    public final static String ATTR_UserName = "UserName";
    public final static String ATTR_FullUserName = "FullUserName";
    public final static String ATTR_OSIdentity = "OSIdentity";
    public final static String ATTR_AuthenticationType = "AuthenticationType";
    public final static String ATTR_Address = "Address";
    public final static String ATTR_Company = "Company";
    public final static String ATTR_Telephone = "Telephone";
    public final static String ATTR_Fax = "Fax";
    public final static String ATTR_Email = "Email";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(User.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OrgUserDN);
                ai.setJavaName(ATTR_OrgUserDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AuthUserDN);
                ai.setJavaName(ATTR_AuthUserDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_UserName);
                ai.setJavaName(ATTR_UserName);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_FullUserName);
                ai.setJavaName(ATTR_FullUserName);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OSIdentity);
                ai.setJavaName(ATTR_OSIdentity);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_AuthenticationType);
                ai.setJavaName(ATTR_AuthenticationType);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Address);
                ai.setJavaName(ATTR_Address);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Company);
                ai.setJavaName(ATTR_Company);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Telephone);
                ai.setJavaName(ATTR_Telephone);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Fax);
                ai.setJavaName(ATTR_Fax);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_Email);
                ai.setJavaName(ATTR_Email);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
        }
        return s_classInfo;
    }

    public UserBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getOrgUserDN()
    {
        return getStringProperty(ATTR_OrgUserDN);
    }

    public void setOrgUserDN(String value)
    {
        setProperty(ATTR_OrgUserDN, value, 0);
    }

    public String getAuthUserDN()
    {
        return getStringProperty(ATTR_AuthUserDN);
    }

    public void setAuthUserDN(String value)
    {
        setProperty(ATTR_AuthUserDN, value, 0);
    }

    public String getUserName()
    {
        return getStringProperty(ATTR_UserName);
    }

    public void setUserName(String value)
    {
        setProperty(ATTR_UserName, value, 0);
    }

    public String getFullUserName()
    {
        return getStringProperty(ATTR_FullUserName);
    }

    public void setFullUserName(String value)
    {
        setProperty(ATTR_FullUserName, value, 0);
    }

    public String getOSIdentity()
    {
        return getStringProperty(ATTR_OSIdentity);
    }

    public void setOSIdentity(String value)
    {
        setProperty(ATTR_OSIdentity, value, 0);
    }

    public String getAuthenticationType()
    {
        return getStringProperty(ATTR_AuthenticationType);
    }

    public void setAuthenticationType(String value)
    {
        setProperty(ATTR_AuthenticationType, value, 0);
    }

    public String getAddress()
    {
        return getStringProperty(ATTR_Address);
    }

    public void setAddress(String value)
    {
        setProperty(ATTR_Address, value, 0);
    }

    public String getCompany()
    {
        return getStringProperty(ATTR_Company);
    }

    public void setCompany(String value)
    {
        setProperty(ATTR_Company, value, 0);
    }

    public String getTelephone()
    {
        return getStringProperty(ATTR_Telephone);
    }

    public void setTelephone(String value)
    {
        setProperty(ATTR_Telephone, value, 0);
    }

    public String getFax()
    {
        return getStringProperty(ATTR_Fax);
    }

    public void setFax(String value)
    {
        setProperty(ATTR_Fax, value, 0);
    }

    public String getEmail()
    {
        return getStringProperty(ATTR_Email);
    }

    public void setEmail(String value)
    {
        setProperty(ATTR_Email, value, 0);
    }





}
