/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.busobject.BusObjectIterator;
import com.cordys.cpc.bsf.classinfo.AttributeInfo;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;
import com.cordys.cpc.bsf.listeners.constraint.NumberValidator;


public abstract class UIUserTeamsBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    public final static String ATTR_OrgUserDN = "OrgUserDN";
    public final static String ATTR_PrincipleUnitID = "PrincipleUnitID";
    private final static String REL_TeamRoles = "COMP:TeamRoles";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UIUserTeams.class);
            s_classInfo.setUIDElements(new String[]{ATTR_OrgUserDN});
            {
                AttributeInfo ai = new AttributeInfo(ATTR_OrgUserDN);
                ai.setJavaName(ATTR_OrgUserDN);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                AttributeInfo ai = new AttributeInfo(ATTR_PrincipleUnitID);
                ai.setJavaName(ATTR_PrincipleUnitID);
                ai.setAttributeClass(String.class);
                s_classInfo.addAttributeInfo(ai);
            }
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_TeamRoles);
                ri.setName("TeamRoles");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UIUserTeams.TeamRoles.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public UIUserTeamsBase(BusObjectConfig config)
    {
        super(config);
    }

    public String getOrgUserDN()
    {
        return getStringProperty(ATTR_OrgUserDN);
    }

    public void setOrgUserDN(String value)
    {
        setProperty(ATTR_OrgUserDN, value, 0);
    }

    public String getPrincipleUnitID()
    {
        return getStringProperty(ATTR_PrincipleUnitID);
    }

    public void setPrincipleUnitID(String value)
    {
        setProperty(ATTR_PrincipleUnitID, value, 0);
    }

    public UIUserTeams.TeamRoles getTeamRolesObject()
    {
        return (UIUserTeams.TeamRoles)getSingleRelationObject(REL_TeamRoles);
    }

    public UIUserTeams.TeamRoles setTeamRolesObject(UIUserTeams.TeamRoles a_TeamRoles)
    {
        return(UIUserTeams.TeamRoles)_getSingleRelation(REL_TeamRoles, true).setLocalObject(a_TeamRoles);
    }


    public static abstract class TeamRolesBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
    {
        // tags used in the XML document
        private final static String REL_TeamRole = "COMP:TeamRole";
        private static ClassInfo s_classInfo = null;
        public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
        {
            if ( s_classInfo == null )//NOPMD
            {
                s_classInfo = newClassInfo(UIUserTeams.TeamRoles.class);
                s_classInfo.setUIDElements(new String[]{});
                {
                    RelationInfo_Composite ri = new RelationInfo_Composite(REL_TeamRole);
                    ri.setName("TeamRole");
                    ri.setMultiOcc(true);
                    ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UIUserTeams.TeamRoles.TeamRole.class);
                    s_classInfo.addRelationInfo(ri);
                }
            }
            return s_classInfo;
        }

        public TeamRolesBase(BusObjectConfig config)
        {
            super(config);
        }

        public BusObjectIterator<UIUserTeams.TeamRoles.TeamRole> getTeamRoleObjects()
        {
            return getMultiRelationObjects(REL_TeamRole);
        }

        public UIUserTeams.TeamRoles.TeamRole addTeamRoleObject(UIUserTeams.TeamRoles.TeamRole a_TeamRole)
        {
            return (UIUserTeams.TeamRoles.TeamRole)_getMultiRelation(REL_TeamRole, true).addObject(a_TeamRole);
        }

        public void removeTeamRoleObject(UIUserTeams.TeamRoles.TeamRole a_TeamRole)
        {
            _getMultiRelation(REL_TeamRole, true).removeObject(a_TeamRole);
        }

        public static abstract class TeamRoleBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
        {
            // tags used in the XML document
            public final static String ATTR_SeqNo = "SeqNo";
            public final static String ATTR_UnitID = "UnitID";
            public final static String ATTR_UnitName = "UnitName";
            public final static String ATTR_UnitQName = "UnitQName";
            public final static String ATTR_RoleDN = "RoleDN";
            public final static String ATTR_Assigned = "Assigned";
            public final static String ATTR_AssignmentID = "AssignmentID";
            public final static String ATTR_Description = "Description";
            private static ClassInfo s_classInfo = null;
            public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
            {
                if ( s_classInfo == null )//NOPMD
                {
                    s_classInfo = newClassInfo(UIUserTeams.TeamRoles.TeamRole.class);
                    s_classInfo.setUIDElements(new String[]{});
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_SeqNo);
                        ai.setJavaName(ATTR_SeqNo);
                        ai.setAttributeClass(int.class);
                        NumberValidator v = new NumberValidator(ATTR_SeqNo);
                        ai.addConstraintHandler(v);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_UnitID);
                        ai.setJavaName(ATTR_UnitID);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_UnitName);
                        ai.setJavaName(ATTR_UnitName);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_UnitQName);
                        ai.setJavaName(ATTR_UnitQName);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_RoleDN);
                        ai.setJavaName(ATTR_RoleDN);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_Assigned);
                        ai.setJavaName(ATTR_Assigned);
                        ai.setAttributeClass(boolean.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_AssignmentID);
                        ai.setJavaName(ATTR_AssignmentID);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                    {
                        AttributeInfo ai = new AttributeInfo(ATTR_Description);
                        ai.setJavaName(ATTR_Description);
                        ai.setAttributeClass(String.class);
                        s_classInfo.addAttributeInfo(ai);
                    }
                }
                return s_classInfo;
            }

            public TeamRoleBase(BusObjectConfig config)
            {
                super(config);
            }

            public int getSeqNo()
            {
                return getIntProperty(ATTR_SeqNo);
            }

            public void setSeqNo(int value)
            {
                setProperty(ATTR_SeqNo, value, 0);
            }

            public String getUnitID()
            {
                return getStringProperty(ATTR_UnitID);
            }

            public void setUnitID(String value)
            {
                setProperty(ATTR_UnitID, value, 0);
            }

            public String getUnitName()
            {
                return getStringProperty(ATTR_UnitName);
            }

            public void setUnitName(String value)
            {
                setProperty(ATTR_UnitName, value, 0);
            }

            public String getUnitQName()
            {
                return getStringProperty(ATTR_UnitQName);
            }

            public void setUnitQName(String value)
            {
                setProperty(ATTR_UnitQName, value, 0);
            }

            public String getRoleDN()
            {
                return getStringProperty(ATTR_RoleDN);
            }

            public void setRoleDN(String value)
            {
                setProperty(ATTR_RoleDN, value, 0);
            }

            public boolean getAssigned()
            {
                return getBooleanProperty(ATTR_Assigned);
            }

            public void setAssigned(boolean value)
            {
                setProperty(ATTR_Assigned, value, 0);
            }

            public String getAssignmentID()
            {
                return getStringProperty(ATTR_AssignmentID);
            }

            public void setAssignmentID(String value)
            {
                setProperty(ATTR_AssignmentID, value, 0);
            }

            public String getDescription()
            {
                return getStringProperty(ATTR_Description);
            }

            public void setDescription(String value)
            {
                setProperty(ATTR_Description, value, 0);
            }

        }
    }
}
