/*
  This class has been generated by the Code Generator
*/

package com.cordys.coe.tools.useradmin.ui;

import com.cordys.cpc.bsf.busobject.BusObjectConfig;
import com.cordys.cpc.bsf.classinfo.ClassInfo;
import com.cordys.cpc.bsf.classinfo.RelationInfo_Composite;


public abstract class UIUserUpdateDataBase extends com.cordys.cpc.bsf.busobject.CustomBusObject
{
    // tags used in the XML document
    private final static String REL_Assignments = "AGGR:Assignments";
    private static ClassInfo s_classInfo = null;
    public static ClassInfo _getClassInfo()//NOPMD framework ensures this is thread safe
    {
        if ( s_classInfo == null )//NOPMD
        {
            s_classInfo = newClassInfo(UIUserUpdateData.class);
            s_classInfo.setUIDElements(new String[]{});
            {
                RelationInfo_Composite ri = new RelationInfo_Composite(REL_Assignments);
                ri.setName("Assignments");
                ri.setMultiOcc(false);
                ri.setRelatedClass(com.cordys.coe.tools.useradmin.ui.UIAssignments.class);
                s_classInfo.addRelationInfo(ri);
            }
        }
        return s_classInfo;
    }

    public UIUserUpdateDataBase(BusObjectConfig config)
    {
        super(config);
    }

    public UIAssignments getAssignmentsObject()
    {
        return (UIAssignments)getSingleRelationObject(REL_Assignments);
    }

    public UIAssignments setAssignmentsObject(UIAssignments a_UIAssignments)
    {
        return(UIAssignments)_getSingleRelation(REL_Assignments, true).setLocalObject(a_UIAssignments);
    }

}
